license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="LexRei"
[[mixins]]
config="easymagicbeer.mixins.json"

description='''
Compatibility between Easy Magic and BEER, allowing Easy Magic to use BEER's expanded enchanting table range.
'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="easymagic"
type="required"
versionRange="[26.1.0,26.2)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="beer"
type="required"
versionRange="[1.4.3,1.5)"
ordering="AFTER"
side="BOTH"
